### ISSUE TITLE
[Feature] 데이터 Cache 구현 

### ISSUE THREAD

**Issue by Chelly142** [GraduationDku/tastyHub#148]
Description
> 기능 요구사항 상세 설명
데이터 Cache 구현 

Progress
- [ ] 할일1
- [ ] 할일2
- [ ] 할일3

**Comment by skyriv213** [comment]
캐시로 요청 보낸 로직에서 똑같은 로직 진행 시 403 등의 요청 에러 발생

**Comment by skyriv213** [comment]
fix - require <(cache)> : 레디스 포트 중복 문제로 인한 캐시기능 동작 x 

redis 포트 변경 및 설정 파일 추가 작성
