### ISSUE TITLE
[Feature] env - S3 사용 이미지 구현

### ISSUE THREAD

**Issue by skyriv213** [GraduationDku/tastyHub#22]
Description
> 기능 요구사항 상세 설명
env - S3 사용 이미지 구현

Progress
- [x] @sep037 : 기존 로직 중 이미지 들어가는 방식으로 리팩토링
- [x] @Chelly142 : S3 환경세팅 및 기존 로직 리팩토링

**Comment by sep037** [comment]
ㅂ2
